###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      container_name: sigtar-mysql
      working_dir: /application
      volumes:
        - ./src:/application
        - ./mysql/conf/logs.cnf:/etc/mysql/conf.d/logs.cnf
        - ./mysql/logs:/var/log/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=
        - MYSQL_DATABASE=
        - MYSQL_USER=
        - MYSQL_PASSWORD=
      ports:
        - "8082:3306"
      command:
        - "--default-authentication-plugin=mysql_native_password" # fix for laravel 5.7

    webserver:
      image: nginx:alpine
      container_name: sigtar-webserver
      working_dir: /application
      volumes:
          - ./src:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8088:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: sigtar-php-fpm
      working_dir: /application
      volumes:
        - ./src:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

